# Generated by Django 5.2.4 on 2025-09-15 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_evento_organizador'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.PositiveIntegerField()),
                ('sold', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.evento')),
            ],
            options={
                'verbose_name': 'Tipo de Boleto',
                'verbose_name_plural': 'Tipos de Boleto',
                'constraints': [models.CheckConstraint(condition=models.Q(('sold__gte', 0)), name='tickettype_sold_gte_0'), models.CheckConstraint(condition=models.Q(('capacity__gte', 0)), name='tickettype_capacity_gte_0'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='tickettype_price_gte_0')],
            },
        ),
    ]
