# Generated by Django 5.2.7 on 2025-11-04 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("events", "0006_alter_categoriaevento_descripcion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asistente",
            name="historial_compras",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Historial de compras"
            ),
        ),
        migrations.AlterField(
            model_name="asistente",
            name="preferencias",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Preferencias"
            ),
        ),
        migrations.AlterField(
            model_name="asistente",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil_asistente",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="nombre",
            field=models.CharField(max_length=200, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="tipo",
            field=models.CharField(
                choices=[("asistente", "Asistente"), ("organizador", "Organizador")],
                default="asistente",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="organizador",
            name="empresa",
            field=models.CharField(max_length=200, verbose_name="Empresa"),
        ),
        migrations.AlterField(
            model_name="organizador",
            name="eventos_publicados",
            field=models.ManyToManyField(
                blank=True,
                related_name="organizadores",
                to="events.evento",
                verbose_name="Eventos publicados",
            ),
        ),
        migrations.AlterField(
            model_name="organizador",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil_organizador",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
    ]
