# Generated by Django 5.2.7 on 2025-11-05 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_asistente_historial_compras_and_more"),
        ("events", "0006_alter_categoriaevento_descripcion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asistente",
            name="historial_compras",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="asistente",
            name="preferencias",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="asistente",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil_asistente",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="tipo",
            field=models.CharField(
                choices=[("asistente", "Asistente"), ("organizador", "Organizador")],
                default="asistente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="organizador",
            name="empresa",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="organizador",
            name="eventos_publicados",
            field=models.ManyToManyField(
                blank=True, related_name="organizadores", to="events.evento"
            ),
        ),
        migrations.AlterField(
            model_name="organizador",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil_organizador",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
