# Generated by Django 5.2.6 on 2025-11-03 22:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_categoriaevento_descripcion_and_more"),
        ("orders", "0003_tickethold"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de reserva"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("confirmed", "Confirmada"),
                            ("paid", "Pagada"),
                            ("cancelled", "Cancelada"),
                            ("refunded", "Reembolsada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado de la reserva",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto total"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de cancelación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "ordering": ["-booking_date"],
            },
        ),
        migrations.CreateModel(
            name="BookingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Número de boletos de este tipo",
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio unitario"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Subtotal"
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de reserva",
                "verbose_name_plural": "Items de reserva",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Orden",
                "verbose_name_plural": "Órdenes",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Item de orden",
                "verbose_name_plural": "Items de orden",
            },
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"verbose_name": "Boleto", "verbose_name_plural": "Boletos"},
        ),
        migrations.AlterModelOptions(
            name="tickethold",
            options={
                "verbose_name": "Reserva temporal",
                "verbose_name_plural": "Reservas temporales",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                default="created",
                help_text="Estado de la orden: created, paid, refunded",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Monto total"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualización"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="events.evento",
                verbose_name="Evento",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="line_total",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Total de línea"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.order",
                verbose_name="Orden",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Cantidad"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="ticket_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="events.tickettype",
                verbose_name="Tipo de boleto",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Precio unitario"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="events.evento",
                verbose_name="Evento",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="is_used",
            field=models.BooleanField(default=False, verbose_name="Usado"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="orders.order",
                verbose_name="Orden",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="events.tickettype",
                verbose_name="Tipo de boleto",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="unique_code",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Código único",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AlterField(
            model_name="tickethold",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="tickethold",
            name="expires_at",
            field=models.DateTimeField(
                db_index=True, verbose_name="Fecha de expiración"
            ),
        ),
        migrations.AlterField(
            model_name="tickethold",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Cantidad"),
        ),
        migrations.AlterField(
            model_name="tickethold",
            name="session_key",
            field=models.CharField(
                db_index=True, max_length=64, verbose_name="Clave de sesión"
            ),
        ),
        migrations.AlterField(
            model_name="tickethold",
            name="ticket_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holds",
                to="events.tickettype",
                verbose_name="Tipo de boleto",
            ),
        ),
        migrations.AlterField(
            model_name="tickethold",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "-created_at"], name="orders_orde_user_id_0ae59f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="orders_orde_status_c6dd84_idx"),
        ),
        migrations.AddField(
            model_name="booking",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="events.evento",
                verbose_name="Evento",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="bookingitem",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.booking",
                verbose_name="Reserva",
            ),
        ),
        migrations.AddField(
            model_name="bookingitem",
            name="ticket_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="events.tickettype",
                verbose_name="Tipo de boleto",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["user", "-booking_date"], name="orders_book_user_id_4eb539_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["event", "status"], name="orders_book_event_i_b628e9_idx"
            ),
        ),
    ]
