

# Generated by Django 5.2.x on 2025-09-12

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaEvento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
            ],
            options={
                "verbose_name": "Categoría de Evento",
                "verbose_name_plural": "Categorías de Eventos",
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=200)),
                ("fecha", models.DateField()),
                ("lugar", models.CharField(max_length=200)),
                ("cupos_disponibles", models.PositiveIntegerField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("organizador", models.CharField(max_length=100, default="Sin Organizador")),
                ("categoria", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="eventos", to="events.categoriaevento")),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["-fecha", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("capacity", models.PositiveIntegerField()),
                ("sold", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ticket_types", to="events.evento")),
            ],
            options={
                "verbose_name": "Tipo de boleto",
                "verbose_name_plural": "Tipos de boleto",
            },
        ),
    ]
