# Generated by Django 5.2.6 on 2025-09-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="organizador",
            field=models.CharField(default="Sin Organizador", max_length=100),
        ),
    ]
