# Generated by Django 5.2.6 on 2025-09-15 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_evento_organizador"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="descripcion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="estado",
            field=models.CharField(
                choices=[
                    ("borrador", "Borrador"),
                    ("publicado", "Publicado"),
                    ("pausado", "Pausado"),
                ],
                default="borrador",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="organizador",
            field=models.ForeignKey(
                limit_choices_to={"tipo": "organizador"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos_organizados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
