# Generated by Django 5.2.6 on 2025-09-15 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_evento_descripcion_evento_estado_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="organizador",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"tipo": "organizador"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos_organizados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
