# Generated by Django 5.2.6 on 2025-11-03 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_tickettype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaevento",
            name="descripcion",
            field=models.TextField(verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="categoriaevento",
            name="nombre",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="eventos",
                to="events.categoriaevento",
                verbose_name="Categoría",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="cupos_disponibles",
            field=models.PositiveIntegerField(verbose_name="Cupos disponibles"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="descripcion",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="estado",
            field=models.CharField(
                choices=[
                    ("borrador", "Borrador"),
                    ("publicado", "Publicado"),
                    ("pausado", "Pausado"),
                ],
                default="borrador",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="fecha",
            field=models.DateField(verbose_name="Fecha"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="fecha_actualizacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualización"
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="lugar",
            field=models.CharField(max_length=200, verbose_name="Lugar"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="nombre",
            field=models.CharField(max_length=200, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="organizador",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"tipo": "organizador"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos_organizados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Organizador",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="precio",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Precio"
            ),
        ),
        migrations.AlterField(
            model_name="tickettype",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AlterField(
            model_name="tickettype",
            name="capacity",
            field=models.PositiveIntegerField(verbose_name="Capacidad"),
        ),
        migrations.AlterField(
            model_name="tickettype",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_types",
                to="events.evento",
                verbose_name="Evento",
            ),
        ),
        migrations.AlterField(
            model_name="tickettype",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="tickettype",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Precio"
            ),
        ),
        migrations.AlterField(
            model_name="tickettype",
            name="sold",
            field=models.PositiveIntegerField(default=0, verbose_name="Vendidos"),
        ),
    ]
